development:
  AWS_ACCESS_KEY_ID: "AKIAI2CABCOKX5E2K5ZQ"
  AWS_SECRET_ACCESS_KEY: "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"
  AWS_S3_BUCKET: "grassrootsdotorg"

test:
  AWS_ACCESS_KEY_ID: "AKIAI2CABCOKX5E2K5ZQ"
  AWS_SECRET_ACCESS_KEY: "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"
  AWS_S3_BUCKET: "grassrootsdotorg"

production:
  AWS_ACCESS_KEY_ID: "AKIAI2CABCOKX5E2K5ZQ"
  AWS_SECRET_ACCESS_KEY: "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"
  AWS_S3_BUCKET: "grassrootsdotorg"